export const marques = [
    {
        id: 1,
        name: 'braillesense',
        title: 'Braille Sense',
        htmlFor: 'braillesense',
    },
    {
        id: 2,
        name: 'clover3',
        title: 'Clover 3',
        htmlFor: 'clover3',
    },
    {
        id: 3,
        name: 'amelie',
        title: 'Amelie Loupe',
        htmlFor: 'amelie',
    },
    {
        id: 4,
        name: 'moni',
        title: 'Moni Loupe',
        htmlFor: 'moni',
    },
    {
        id: 5,
        name: 'reveal16',
        title: 'Reveal 16',
        htmlFor: 'reveal16',
    },
    {
        id: 6,
        name: 'explor',
        title: 'ExploR',
        htmlFor: 'explor',
    },
    {
        id: 7,
        name: 'ordissimo',
        title: 'Ordissimo',
        htmlFor: 'ordissimo',
    },
    {
        id: 8,
        name: 'apple',
        title: 'Apple',
        htmlFor: 'apple',
    },
    {
        id: 9,
        name: 'android',
        title: 'Android',
        htmlFor: 'android',
    },
    {
        id: 10,
        name: 'android',
        title: 'Android',
        htmlFor: 'android',
    },
    {
        id: 11,
        name: 'facitalab',
        title: 'FacitaLab',
        htmlFor: 'facitalab',
    },
    {
        id: 12,
        name: 'pixstar',
        title: 'PixStar',
        htmlFor: 'pixstar',
    },
    {
        id: 13,
        name: 'cl8000',
        title: 'CL8000',
        htmlFor: 'cl8000',
    },
    {
        id: 14,
        name: 'cl7000',
        title: 'CL8700',
        htmlFor: 'cl8700',
    },
    {
        id: 15,
        name: 'cl7000',
        title: 'CL8700',
        htmlFor: 'cl8700',
    },
    {
        id: 16,
        name: 'geemarc',
        title: 'GeeMarc',
        htmlFor: 'geemarc',
    },
    {
        id: 17,
        name: 'konrow',
        title: 'KonRow',
        htmlFor: 'konrow',
    },
    {
        id: 18,
        name: 'smartvision',
        title: 'Smartvision',
        htmlFor: 'smartvision',
    },
]

export const couleurs = [
    {
        id: 1,
        name: 'rouge',
        title: 'Rouge',
        htmlFor: 'rouge',
    },
    {
        id: 2,
        name: 'bleu',
        title: 'Bleu',
        htmlFor: 'bleu',
    },
    {
        id: 3,
        name: 'noir',
        title: 'Noir',
        htmlFor: 'noir',
    },
    {
        id: 4,
        name: 'jaune',
        title: 'Jaune',
        htmlFor: 'jaune',
    },
    {
        id: 5,
        name: 'vert',
        title: 'Vert',
        htmlFor: 'vert',
    },
    {
        id: 6,
        name: 'orange',
        title: 'Orange',
        htmlFor: 'orange',
    },
    {
        id: 7,
        name: 'rose',
        title: 'Rose',
        htmlFor: 'rose',
    },
    {
        id: 8,
        name: 'blanc',
        title: 'Blanc',
        htmlFor: 'blanc',
    },
    // {
    //     id: 9,
    //     name: 'android',
    //     title: 'Android',
    //     htmlFor: 'android',
    // },
    // {
    //     id: 10,
    //     name: 'android',
    //     title: 'Android',
    //     htmlFor: 'android',
    // },
    // {
    //     id: 11,
    //     name: 'facitalab',
    //     title: 'FacitaLab',
    //     htmlFor: 'facitalab',
    // },
    // {
    //     id: 12,
    //     name: 'pixstar',
    //     title: 'PixStar',
    //     htmlFor: 'pixstar',
    // },
    // {
    //     id: 13,
    //     name: 'cl8000',
    //     title: 'CL8000',
    //     htmlFor: 'cl8000',
    // },
    // {
    //     id: 14,
    //     name: 'cl7000',
    //     title: 'CL8700',
    //     htmlFor: 'cl8700',
    // },
    // {
    //     id: 15,
    //     name: 'cl7000',
    //     title: 'CL8700',
    //     htmlFor: 'cl8700',
    // },
    // {
    //     id: 16,
    //     name: 'geemarc',
    //     title: 'GeeMarc',
    //     htmlFor: 'geemarc',
    // },
    // {
    //     id: 17,
    //     name: 'konrow',
    //     title: 'KonRow',
    //     htmlFor: 'konrow',
    // },
    // {
    //     id: 18,
    //     name: 'smartvision',
    //     title: 'Smartvision',
    //     htmlFor: 'smartvision',
    // },
]

export const categories = [
    {
        id: 1,
        name: 'accessoires',
        title: 'Accessoires',
        htmlFor: 'accesoires',
    },
    {
        id: 2,
        name: 'braille',
        title: 'Braille',
        htmlFor: 'braille',
    },
    {
        id: 3,
        name: 'loupeelectronique',
        title: 'Loupe Eléctronique',
        htmlFor: 'loupeelectronique',
    },
    {
        id: 4,
        name: 'lunettesloupes',
        title: 'Lunettes Loupe',
        htmlFor: 'lunettesloupes',
    },
    {
        id: 5,
        name: 'montres',
        title: 'Montres',
        htmlFor: 'montres',
    },
    {
        id: 6,
        name: 'ordinateur',
        title: 'Ordinateur',
        htmlFor: 'ordinateur',
    },
    {
        id: 7,
        name: 'smartphones',
        title: 'Smartphones',
        htmlFor: 'smartphones',
    },
    {
        id: 8,
        name: 'tablettes',
        title: 'Tablettes',
        htmlFor: 'tablettes',
    },
    {
        id: 9,
        name: 'telephonesenior',
        title: 'Téléphones Senior',
        htmlFor: 'telephonesenior',
    },
    {
        id: 10,
        name: 'tout',
        title: 'Tout',
        htmlFor: 'tout',
    }
]
