export const marques = [
    {
        id: 1,
        name: 'braillesense',
        title: 'Braille Sense',
        htmlFor: 'braillesense',
    },
    {
        id: 2,
        name: 'clover3',
        title: 'Clover 3',
        htmlFor: 'clover3',
    },
    {
        id: 3,
        name: 'amelie',
        title: 'Amelie Loupe',
        htmlFor: 'amelie',
    },
    {
        id: 4,
        name: 'moni',
        title: 'Moni Loupe',
        htmlFor: 'moni',
    },
    {
        id: 5,
        name: 'reveal16',
        title: 'Reveal 16',
        htmlFor: 'reveal16',
    },
    {
        id: 6,
        name: 'explor',
        title: 'ExploR',
        htmlFor: 'explor',
    },
    {
        id: 7,
        name: 'ordissimo',
        title: 'Ordissimo',
        htmlFor: 'ordissimo',
    },
    {
        id: 8,
        name: 'apple',
        title: 'Apple',
        htmlFor: 'apple',
    },
    {
        id: 9,
        name: 'android',
        title: 'Android',
        htmlFor: 'android',
    },
    {
        id: 10,
        name: 'android',
        title: 'Android',
        htmlFor: 'android',
    },
    {
        id: 11,
        name: 'facitalab',
        title: 'FacitaLab',
        htmlFor: 'facitalab',
    },
    {
        id: 12,
        name: 'pixstar',
        title: 'PixStar',
        htmlFor: 'pixstar',
    },
    {
        id: 13,
        name: 'cl8000',
        title: 'CL8000',
        htmlFor: 'cl8000',
    },
    {
        id: 14,
        name: 'cl7000',
        title: 'CL8700',
        htmlFor: 'cl8700',
    },
    {
        id: 15,
        name: 'cl7000',
        title: 'CL8700',
        htmlFor: 'cl8700',
    },
    {
        id: 16,
        name: 'geemarc',
        title: 'GeeMarc',
        htmlFor: 'geemarc',
    },
    {
        id: 17,
        name: 'konrow',
        title: 'KonRow',
        htmlFor: 'konrow',
    },
    {
        id: 18,
        name: 'smartvision',
        title: 'Smartvision',
        htmlFor: 'smartvision',
    },
]