export const couleurs = [
    {
        id: 1,
        name: 'rouge',
        title: 'Rouge',
        htmlFor: 'rouge',
    },
    {
        id: 2,
        name: 'bleu',
        title: 'Bleu',
        htmlFor: 'bleu',
    },
    {
        id: 3,
        name: 'noir',
        title: 'Noir',
        htmlFor: 'noir',
    },
    {
        id: 4,
        name: 'jaune',
        title: 'Jaune',
        htmlFor: 'jaune',
    },
    {
        id: 5,
        name: 'vert',
        title: 'Vert',
        htmlFor: 'vert',
    },
    {
        id: 6,
        name: 'orange',
        title: 'Orange',
        htmlFor: 'orange',
    },
    {
        id: 7,
        name: 'rose',
        title: 'Rose',
        htmlFor: 'rose',
    },
    {
        id: 8,
        name: 'blanc',
        title: 'Blanc',
        htmlFor: 'blanc',
    },
    // {
    //     id: 9,
    //     name: 'android',
    //     title: 'Android',
    //     htmlFor: 'android',
    // },
    // {
    //     id: 10,
    //     name: 'android',
    //     title: 'Android',
    //     htmlFor: 'android',
    // },
    // {
    //     id: 11,
    //     name: 'facitalab',
    //     title: 'FacitaLab',
    //     htmlFor: 'facitalab',
    // },
    // {
    //     id: 12,
    //     name: 'pixstar',
    //     title: 'PixStar',
    //     htmlFor: 'pixstar',
    // },
    // {
    //     id: 13,
    //     name: 'cl8000',
    //     title: 'CL8000',
    //     htmlFor: 'cl8000',
    // },
    // {
    //     id: 14,
    //     name: 'cl7000',
    //     title: 'CL8700',
    //     htmlFor: 'cl8700',
    // },
    // {
    //     id: 15,
    //     name: 'cl7000',
    //     title: 'CL8700',
    //     htmlFor: 'cl8700',
    // },
    // {
    //     id: 16,
    //     name: 'geemarc',
    //     title: 'GeeMarc',
    //     htmlFor: 'geemarc',
    // },
    // {
    //     id: 17,
    //     name: 'konrow',
    //     title: 'KonRow',
    //     htmlFor: 'konrow',
    // },
    // {
    //     id: 18,
    //     name: 'smartvision',
    //     title: 'Smartvision',
    //     htmlFor: 'smartvision',
    // },
]